name: hola_home
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  country_code_picker:
    path: packages/country_code_picker
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  mobx: ^2.1.3
  provider: ^6.0.5
  rating_summary:
    path: packages/rating_summary

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  lint: ^2.1.2
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/png/app/
    - assets/png/contact_us/
    - assets/png/flags/
    - assets/png/no_result/
    - assets/png/payment/
    - assets/png/property/
    - assets/png/profile/
    - assets/png/signup_login/
    - assets/png/splash/
    - assets/svg/
    - assets/svg/app/
    - assets/svg/booking/
    - assets/svg/company_logo/
    - assets/svg/contact_us/
    - assets/svg/forgot_password/
    - assets/svg/property_description/
    - assets/svg/profile_icons/
    - assets/svg/search/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          # style: italic

    - family: HolaHome
      fonts:
        - asset: assets/hola_home_icons/HolaHome.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
